name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ newactiondemo/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Run my own container action
        id: hello-action
        uses: ./newactiondemo
        with:
          who-to-greet: '@dcottagit'

      - name: Output time set in the container
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
